# Generated by Django 4.0.3 on 2022-03-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chars', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=50, verbose_name='At resmi')),
            ],
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
